import './styles/globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className='w-full h-full z-0 p-0 m-0 bg-light dark:bg-dark dark:text-light'>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}