import './styles/globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-w-full w-full h-full z-0 p-0 m-0 bg-light dark:bg-dark dark:text-light'>
        <Navbar/>
          {children}
        <Footer/>
        </div>

      </body>
    </html>
  )
}